apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: todoapp-db-persistent-volume-claim
  namespace: todoapp
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi