apiVersion: v1
kind: PersistentVolume
metadata:
  name: todoapp-db-storage
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/postgres-data"