apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "todoapp.fullname" . }}-db-storage
  labels:
  {{- include "todoapp.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /opt/postgres-data
  storageClassName: standard