apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todoapp.fullname" . }}-postgres-secret
  labels:
  {{- include "todoapp.labels" . | nindent 4 }}
data:
  POSTGRES_PASSWORD: {{ required "postgresSecret.postgresPassword is required" .Values.postgresSecret.postgresPassword
    | b64enc | quote }}
  POSTGRES_USER: {{ required "postgresSecret.postgresUser is required" .Values.postgresSecret.postgresUser
    | b64enc | quote }}
type: Opaque